spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: embedded
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
      data-locations: app-data.sql

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    ROOT: ERROR
