spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: always

  main:
    allow-circular-references: true
  sql:
    init:
      data-locations: data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: none

  jersey:
    application-path:
