drop table if exists author CASCADE;
 
drop table if exists book CASCADE;
 
drop table if exists comment CASCADE;
 
drop table if exists genre CASCADE;
 
create table author (
                        id integer generated by default as identity,
                        name varchar(255),
                        primary key (id)
);
 
create table book (
                      id integer generated by default as identity,
                      title varchar(255),
                      author_id integer,
                      genre_id integer,
                      primary key (id)
);
 
create table comment (
                         id integer generated by default as identity,
                         comment varchar(255),
                         book_id integer,
                         primary key (id)
);
 
create table genre (
                       id integer generated by default as identity,
                       genre varchar(255),
                       primary key (id)
);
 
alter table book
    add constraint FKklnrv3weler2ftkweewlky958
        foreign key (author_id)
            references author;
 
alter table book
    add constraint FKm1t3yvw5i7olwdf32cwuul7ta
        foreign key (genre_id)
            references genre;
 
alter table comment
    add constraint FKkko96rdq8d82wm91vh2jsfak7
        foreign key (book_id)
            references book;
